name: PYPI

on:
  workflow_dispatch:

jobs:
  pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 2

      - name: Publish package on PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
